name: vtn_flutter_pdf


environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: '>=0.18.1 <0.20.0'
  xml: ">=6.5.0 <7.0.0"
  vtn_flutter_core:
    path: ../vtn_flutter_core
  crypto: ">=3.0.0 <4.0.0"
  convert: ">=3.0.0 <4.0.0"
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter